[package]
name = "daml-macro"
version = "0.3.0"
authors = ["drsk0 <drsk0@proton.me>", "FujiApple <fujiapple852@gmail.com>"]
description = "Helper macros for working with the Daml Ledger API"
readme = "README.md"
repository = "https://github.com/drsk0/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "macro", "api", "ledger"]
categories = ["development-tools"]
edition = "2024"
rust-version = "1.96.0"

[dependencies]
daml-grpc = { version = "0.3.0", path = "../daml-grpc" }
chrono = { workspace = true }
bigdecimal = { workspace = true }

[dev-dependencies]
daml = { path = "../daml", features = [ "grpc", "macros" ] }