//! Daml codegen demo (placeholder).
//!
//! The original v1 demo ran a `daml_codegen` build.rs against an
//! LF 1.14 DAR, then exercised the generated `RentalProposal` /
//! `RentalAgreement` templates via `DamlSimpleExecutor`. Both
//! pieces are blocked on Phase 7 / Phase 8 deliverables:
//!
//! - Phase 7 will check in an LF2 DAR (the existing
//!   `rental-0_1_0-sdk_1_18_1-lf_1_14.dar` is rejected by the
//!   LF2-only `daml-lf` with `UnknownVersion("14")`).
//! - The codegen surface now emits `template_id()` via
//!   package-name (Phase 4a), `impl <Interface> for ...ContractId`
//!   blocks for each implemented interface (Phase 4b), and
//!   `<iface>_<choice>_command` exercise methods (Phase 4c) — the
//!   demo should grow an interface implementation to exercise
//!   that surface.
//! - Phase 8 will provide the integration harness (a Canton
//!   sandbox started via `canton-sandbox` from the
//!   `nix develop` shell) so the demo can actually run.
//!
//! Once those land, this main can:
//!   1. include the autogenerated module produced by build.rs,
//!   2. connect to `localhost:5011` (no auth on the dev sandbox),
//!   3. create a contract via `<Type>::create_command()` →
//!      `command_service().submit_and_wait_for_transaction(...)`,
//!   4. exercise the inherited interface choice via
//!      `<contract_id>.<iface>_<choice>_command(...)`.

fn main() {
    println!("codegen-demo is a v2 rewrite stub. See module docs.");
}
