[package]
name = "grpc-demo"
version = "0.1.0"
authors = ["drsk0 <drsk0@proton.me>", "FujiApple <fujiapple852@gmail.com>"]
description = "Daml GRPC API demo application"
repository = "https://github.com/drsk0/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2024"
rust-version = "1.96.0"

publish = false

[dependencies]
daml = { path = "../../daml", features = [ "grpc", "util", "macros" ] }
tokio = { version = "1.52", features = [ "macros", "rt-multi-thread" ] }
anyhow = "1.0.103"

[workspace]