#![allow(clippy::all, clippy::pedantic)]

// Daml Ledger API v2 protobuf definitions, generated by tonic-build from
// resources/protobuf/com/daml/ledger/api/v2/**.
pub mod com {
    pub mod daml {
        pub mod ledger {
            pub mod api {
                pub mod v2 {
                    include!(concat!(env!("OUT_DIR"), "/com.daml.ledger.api.v2.rs"));
                    pub mod admin {
                        include!(concat!(env!("OUT_DIR"), "/com.daml.ledger.api.v2.admin.rs"));
                    }
                    pub mod testing {
                        include!(concat!(env!("OUT_DIR"), "/com.daml.ledger.api.v2.testing.rs"));
                    }
                    pub mod interactive {
                        include!(concat!(env!("OUT_DIR"), "/com.daml.ledger.api.v2.interactive.rs"));
                        pub mod transaction {
                            pub mod v1 {
                                include!(concat!(
                                    env!("OUT_DIR"),
                                    "/com.daml.ledger.api.v2.interactive.transaction.v1.rs"
                                ));
                            }
                        }
                    }
                }
            }
        }
    }
}

pub mod google {
    pub mod rpc {
        include!(concat!(env!("OUT_DIR"), "/google.rpc.rs"));
    }
}
