[package]
name = "daml-lf"
version = "0.4.0"
authors = ["drsk0 <drsk0@proton.me>", "FujiApple <fujiapple852@gmail.com>"]
description = "API for working with Daml-LF data"
readme = "README.md"
repository = "https://github.com/drsk0/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2024"
rust-version = "1.96.0"
build = "build.rs"

[features]
default = []
full = []

[dependencies]
bytes = { workspace = true }
prost = { workspace = true, features = [ "no-recursion-limit" ] }
prost-derive = { workspace = true }
zip = { version = "8.6.0", default-features = false, features = [ "deflate-flate2-zlib-rs" ] }
yaml-rust2 = "0.11.0"
itertools = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bounded-static = { version = "0.8.0", features = [ "derive" ] }

[dev-dependencies]
trim-margin = "0.1.0"

[build-dependencies]
prost-build = "0.14.4"
itertools = { workspace = true }

[package.metadata.docs.rs]
all-features = true
