[package]
name = "daml-codegen"
version = "0.4.0"
authors = ["drsk0 <drsk0@proton.me>", "FujiApple <fujiapple852@gmail.com>"]
description = "Daml GRPC Ledger API Code Generator"
readme = "README.md"
repository = "https://github.com/drsk0/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2024"
rust-version = "1.96.0"

[dependencies]
daml-lf = { version = "0.4.0", path = "../daml-lf" }
quote = { workspace = true }
proc-macro2 = { workspace = true }
itertools = { workspace = true }
heck = "0.5.0"
regex = "1.12.4"
clap = { version = "4.6.1", features = [ "cargo" ] }
thiserror = { workspace = true }