[package]
name = "daml-codegen"
version = "0.3.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "Daml GRPC Ledger API Code Generator"
readme = "README.md"
repository = "https://github.com/fujiapple852/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2021"
rust-version = "1.75"

[dependencies]
daml-lf = { version = "0.3.0", path = "../daml-lf" }
quote = "1.0.46"
proc-macro2 = "1.0.106"
itertools = "0.15.0"
heck = "0.5.0"
regex = "1.12.4"
clap = { version = "4.6.1", features = [ "cargo" ] }